# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57a78e61174be58378c0e8b2fc62f878eea28262823682c10f499fae0b20f8e8c45035ce8781c562281a434a213a01e7d115663065293cef384b8ca6c7251ddb

test:
  secret_key_base: 0787c40d1ecdda2a4864342e77e8dd831ba68af489dace767c5e71dc32a25b275d0863c44c33f8fdec4ab3cc3f5bd40a135cd73cbfaf5d1da391272c2d1d98d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
